### ISSUE TITLE
Bower package not working

### ISSUE THREAD

**Issue by hernimen** [houseofradon/angular-lory#2]
Hello!
Thanks for the implementation of lory for angular.
The bower package of lory is down, so I downloaded the angular-lory.js.
But by the moment I can't make the example work, and also It's not working on my angular 1.6 current project. 
Thanks

**Comment by Knape** [comment]
Hi

I have pushed a new version of the package (1.0.0) which should fix your problems. I have updated it to work with the latest lory package and angular 1.6.6. Please try it and if you still have problems you can open a new PR, I will close this one. 

.p
